title: PDES-MAS
description: PDES-MAS is a framework and a system (simulation kernel) for the distributed simulation for agent-based systems.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
